/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Dia10;

import java.util.Scanner;

public class App {
    

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
        
        System.out.println("Digite o preço de custo do produto: ");
        float precoCusto = leitor.nextFloat();
        
        System.out.println("Digite o percentual de acréscimo sob o custo do produto: ");
        float percentual = leitor.nextFloat();
        
        float precoTotal = precoCusto + (precoCusto*percentual)/100;
        
        System.out.println("O preço total do produto será de R$" + precoTotal);
        
                
     
        
        
        
    }
}
